// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/authentication.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "gitlab.forge.orange-labs.fr/mahali/services/ms-user/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthenticateRequest struct {
	Provider             string            `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Credentials          map[string]string `protobuf:"bytes,2,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authentication_8c390cf56b8175fa, []int{0}
}
func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(dst, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *AuthenticateRequest) GetCredentials() map[string]string {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type JWT struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWT) Reset()         { *m = JWT{} }
func (m *JWT) String() string { return proto.CompactTextString(m) }
func (*JWT) ProtoMessage()    {}
func (*JWT) Descriptor() ([]byte, []int) {
	return fileDescriptor_authentication_8c390cf56b8175fa, []int{1}
}
func (m *JWT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWT.Unmarshal(m, b)
}
func (m *JWT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWT.Marshal(b, m, deterministic)
}
func (dst *JWT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWT.Merge(dst, src)
}
func (m *JWT) XXX_Size() int {
	return xxx_messageInfo_JWT.Size(m)
}
func (m *JWT) XXX_DiscardUnknown() {
	xxx_messageInfo_JWT.DiscardUnknown(m)
}

var xxx_messageInfo_JWT proto.InternalMessageInfo

func (m *JWT) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JWT) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type Token struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_authentication_8c390cf56b8175fa, []int{2}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthenticateRequest)(nil), "proto.AuthenticateRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.AuthenticateRequest.CredentialsEntry")
	proto.RegisterType((*JWT)(nil), "proto.JWT")
	proto.RegisterType((*Token)(nil), "proto.Token")
}

func init() {
	proto.RegisterFile("proto/authentication.proto", fileDescriptor_authentication_8c390cf56b8175fa)
}

var fileDescriptor_authentication_8c390cf56b8175fa = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x41, 0x6b, 0x32, 0x31,
	0x10, 0x75, 0x5d, 0xfc, 0xd0, 0xd1, 0x83, 0xe4, 0x6b, 0x41, 0x02, 0x82, 0xec, 0xa5, 0x42, 0x71,
	0x17, 0xec, 0x45, 0x3c, 0x14, 0xa4, 0xed, 0x45, 0xe8, 0x65, 0x6b, 0xeb, 0xb1, 0x44, 0x1d, 0x35,
	0xb8, 0x6e, 0xec, 0x24, 0x2b, 0xb5, 0xbf, 0xae, 0x3f, 0xad, 0x6c, 0x36, 0xa8, 0x2d, 0xed, 0x29,
	0xf3, 0xde, 0xbc, 0xf7, 0x26, 0x93, 0x00, 0xdf, 0x91, 0x32, 0x2a, 0x12, 0x99, 0x59, 0x63, 0x6a,
	0xe4, 0x5c, 0x18, 0xa9, 0xd2, 0xd0, 0x92, 0xac, 0x62, 0x0f, 0x7e, 0xbf, 0x92, 0x26, 0x11, 0xb3,
	0x70, 0xa9, 0x68, 0x85, 0xa1, 0x22, 0x91, 0xae, 0xb0, 0x97, 0x88, 0x99, 0x0e, 0x97, 0x14, 0x6d,
	0xc5, 0x5a, 0x24, 0x32, 0xd2, 0x48, 0x7b, 0x39, 0x47, 0x1d, 0x6d, 0x75, 0x2f, 0xd3, 0x48, 0x51,
	0x11, 0x9b, 0x97, 0x45, 0x58, 0xf0, 0xe9, 0xc1, 0xff, 0xd1, 0x69, 0x0a, 0xc6, 0xf8, 0x96, 0xa1,
	0x36, 0x8c, 0x43, 0x75, 0x47, 0x6a, 0x2f, 0x17, 0x48, 0x2d, 0xaf, 0xe3, 0x75, 0x6b, 0xf1, 0x11,
	0xb3, 0x47, 0xa8, 0xcf, 0x09, 0x17, 0xb9, 0x45, 0x24, 0xba, 0x55, 0xee, 0xf8, 0xdd, 0x7a, 0xff,
	0xba, 0x08, 0x0c, 0x7f, 0x09, 0x0b, 0xef, 0x4e, 0xea, 0x87, 0xd4, 0xd0, 0x21, 0x3e, 0xf7, 0xf3,
	0x5b, 0x68, 0xfe, 0x14, 0xb0, 0x26, 0xf8, 0x1b, 0x3c, 0xb8, 0xc9, 0x79, 0xc9, 0x2e, 0xa0, 0xb2,
	0x17, 0x49, 0x86, 0xad, 0xb2, 0xe5, 0x0a, 0x30, 0x2c, 0x0f, 0xbc, 0x60, 0x08, 0xfe, 0x78, 0x3a,
	0xc9, 0x05, 0x46, 0x6d, 0x30, 0x75, 0xa6, 0x02, 0xb0, 0x36, 0x00, 0xbe, 0xef, 0x24, 0xa1, 0x7e,
	0x15, 0xc6, 0x7a, 0xfd, 0xb8, 0xe6, 0x98, 0x91, 0x09, 0xda, 0x50, 0x99, 0x58, 0xdd, 0x31, 0xde,
	0x3b, 0x8b, 0xef, 0x7f, 0xc0, 0xe5, 0xe8, 0xdb, 0x17, 0x3c, 0x15, 0x0f, 0xca, 0x06, 0xd0, 0x38,
	0x5f, 0x94, 0xf1, 0xbf, 0xb7, 0xe7, 0xe0, 0x7a, 0xe3, 0xe9, 0x24, 0x28, 0xb1, 0x2b, 0xa8, 0xbe,
	0x88, 0x44, 0x2e, 0x72, 0x57, 0xc3, 0x75, 0xec, 0x15, 0x78, 0xdd, 0xa1, 0x67, 0x8d, 0x14, 0x94,
	0x66, 0xff, 0x2c, 0xba, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xf7, 0xe1, 0xf0, 0x0b, 0x02,
	0x00, 0x00,
}
