version: "2"

services:
      
  #Reverse Proxy
  reverse-proxy:
    container_name: "reverse-proxy"
    image: "reverse-proxy"
    build :
      context: "./nginx"
      dockerfile: "dockerfile"
    ports:
      - "80:80"
      - "443:443"

  #ms-contributor
  ms-contributor:
    container_name: "ms-contributor"
    image: "ms-contributor"
    depends_on:
      - "ms-authentication"
      - "ms-user"
      - "mongo"
    build : 
      context: "./src/gitlab.forge.orange-labs.fr/mahali/services/ms-contributor"
      dockerfile: "Dockerfile"
    environment:
      GIN_MODE: "debug"
    ports:
      - "8000:8000"

  #ms-authentication
  ms-authentication:
    container_name: "ms-authentication"
    image: "ms-authentication"
    depends_on:
      - "ms-user"
      - "mongo"
    build : 
      context: "./src/gitlab.forge.orange-labs.fr/mahali/services/ms-authentication"
      dockerfile: "Dockerfile"
    environment:
      GIN_MODE: "debug"
    ports:
      - "8001:8000"

  #ms-user
  ms-user:
    container_name: "ms-user"
    image: "ms-user"
    depends_on:
      - "mongo"
    build : 
      context: "./src/gitlab.forge.orange-labs.fr/mahali/services/ms-user"
      dockerfile: "Dockerfile"
    environment:
      GIN_MODE: "debug"
    ports:
      - "8002:8000"

  #MongoDB
  mongo:
    container_name: "mongo"
    image: "mongo:latest"
    ports:
      - "27017:27017"
