version: "2"

services:
      
  #Reverse Proxy
  reverse-proxy:
    container_name: "reverse-proxy"
    image: "reverse-proxy"
    build :
      context: "./nginx"
      dockerfile: "dockerfile"
    links:
      - "mahali-por:mahali-por"
    ports:
      - "80:80"
      - "443:443"
