version: "3"

services:
      
  #Reverse Proxy
  reverse-proxy:
    container_name: "reverse-proxy"
    image: "reverse-proxy"
    build :
      context: "./nginx"
      dockerfile: "dockerfile"
    ports:
      - "80:80"