// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Id struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_04e1aeefd226dc61, []int{0}
}
func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (dst *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(dst, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type User struct {
	// @inject_tag: bson:"_id,omitempty"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`
	// @inject_tag: bson:"username,omitempty"
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty" bson:"username,omitempty"`
	// @inject_tag: bson:"phone_number,omitempty"
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty" bson:"phone_number,omitempty"`
	// @inject_tag: bson:"email_address,omitempty"
	EmailAddress string `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty" bson:"email_address,omitempty"`
	// @inject_tag: bson:"firstname,omitempty"
	Firstname string `protobuf:"bytes,5,opt,name=firstname,proto3" json:"firstname,omitempty" bson:"firstname,omitempty"`
	// @inject_tag: bson:"lastname,omitempty"
	Lastname string `protobuf:"bytes,6,opt,name=lastname,proto3" json:"lastname,omitempty" bson:"lastname,omitempty"`
	// @inject_tag: bson:"locale,omitempty"
	Locale string `protobuf:"bytes,7,opt,name=locale,proto3" json:"locale,omitempty" bson:"locale,omitempty"`
	// @inject_tag: bson:"role,omitempty"
	Role string `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty" bson:"role,omitempty"`
	// @inject_tag: bson:"picture,omitempty"
	Picture              string   `protobuf:"bytes,9,opt,name=picture,proto3" json:"picture,omitempty" bson:"picture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_04e1aeefd226dc61, []int{1}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

type Query struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Filter               string   `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_04e1aeefd226dc61, []int{2}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (dst *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(dst, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Query) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Query) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *Query) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type Result struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Items                []*User  `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_04e1aeefd226dc61, []int{3}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Result) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Result) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Result) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *Result) GetItems() []*User {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Id)(nil), "proto.Id")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Query)(nil), "proto.Query")
	proto.RegisterType((*Result)(nil), "proto.Result")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_user_04e1aeefd226dc61) }

var fileDescriptor_user_04e1aeefd226dc61 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6a, 0xdc, 0x30,
	0x10, 0xc6, 0xd7, 0x5e, 0xdb, 0xc9, 0xce, 0x6e, 0x4a, 0x11, 0x25, 0x08, 0xb7, 0xd0, 0xc4, 0x6d,
	0x21, 0x97, 0x7a, 0x21, 0x7d, 0x82, 0xd2, 0x7f, 0xe4, 0x52, 0xa8, 0x4b, 0xce, 0x41, 0xbb, 0x1e,
	0xa7, 0x02, 0xd9, 0x32, 0x92, 0x1c, 0xc8, 0xb9, 0x2f, 0xd8, 0xe7, 0xe9, 0xa9, 0x68, 0xa4, 0x6d,
	0x4d, 0x09, 0xe4, 0xe4, 0xf9, 0x7d, 0x33, 0xcc, 0xe7, 0x19, 0x0d, 0x3c, 0x1d, 0x8d, 0x76, 0x7a,
	0x3b, 0x59, 0x34, 0x35, 0x85, 0x2c, 0xa7, 0x4f, 0xf9, 0xfc, 0x56, 0xeb, 0x5b, 0x85, 0x5b, 0xa2,
	0xdd, 0xd4, 0x6d, 0xb1, 0x1f, 0xdd, 0x7d, 0xa8, 0xa9, 0x4a, 0x48, 0xaf, 0x5a, 0xf6, 0x0c, 0xf2,
	0x3b, 0xa1, 0x26, 0xe4, 0xc9, 0x59, 0x72, 0xb1, 0x6a, 0x02, 0x54, 0xbf, 0x13, 0xc8, 0xae, 0x2d,
	0x1a, 0xf6, 0x04, 0x52, 0xd9, 0xc6, 0x5c, 0x2a, 0x5b, 0x56, 0xc2, 0xb1, 0xb7, 0x19, 0x44, 0x8f,
	0x3c, 0x25, 0xf5, 0x2f, 0xb3, 0x73, 0xd8, 0x8c, 0x3f, 0xf4, 0x80, 0x37, 0xc3, 0xd4, 0xef, 0xd0,
	0xf0, 0x25, 0xe5, 0xd7, 0xa4, 0x7d, 0x25, 0x89, 0xbd, 0x82, 0x13, 0xec, 0x85, 0x54, 0x37, 0xa2,
	0x6d, 0x0d, 0x5a, 0xcb, 0x33, 0xaa, 0xd9, 0x90, 0xf8, 0x3e, 0x68, 0xec, 0x05, 0xac, 0x3a, 0x69,
	0xac, 0x23, 0x93, 0x9c, 0x0a, 0xfe, 0x09, 0xfe, 0x0f, 0x94, 0x88, 0xc9, 0x22, 0xfc, 0xc1, 0x81,
	0xd9, 0x29, 0x14, 0x4a, 0xef, 0x85, 0x42, 0x7e, 0x44, 0x99, 0x48, 0x8c, 0x41, 0x66, 0xb4, 0x42,
	0x7e, 0x4c, 0x2a, 0xc5, 0x8c, 0xc3, 0xd1, 0x28, 0xf7, 0x6e, 0x32, 0xc8, 0x57, 0x24, 0x1f, 0xb0,
	0x12, 0x90, 0x7f, 0x9b, 0xd0, 0xdc, 0xfb, 0x76, 0xba, 0xeb, 0x2c, 0x3a, 0x5a, 0x40, 0xde, 0x44,
	0xf2, 0x3b, 0x53, 0xb2, 0x97, 0x8e, 0x36, 0x90, 0x37, 0x01, 0xbc, 0x89, 0xd5, 0xc6, 0xc5, 0xb1,
	0x29, 0xf6, 0x1d, 0x3a, 0xa9, 0x1c, 0x9a, 0x38, 0x68, 0xa4, 0xea, 0x67, 0x02, 0x45, 0x83, 0x76,
	0x52, 0xd4, 0xcc, 0x69, 0x27, 0x54, 0xf4, 0x08, 0x30, 0xb3, 0x4e, 0x1f, 0xb6, 0x5e, 0x3e, 0x64,
	0x9d, 0xcd, 0xac, 0xcf, 0x21, 0x97, 0x0e, 0x7b, 0xcb, 0xf3, 0xb3, 0xe5, 0xc5, 0xfa, 0x72, 0x1d,
	0x5e, 0xbd, 0xf6, 0xaf, 0xda, 0x84, 0xcc, 0xe5, 0xaf, 0x04, 0xd6, 0x9e, 0xbf, 0xa3, 0xb9, 0x93,
	0x7b, 0x64, 0xaf, 0xa1, 0xf8, 0x60, 0x50, 0x38, 0x64, 0xf3, 0xea, 0x72, 0x0e, 0xd5, 0x82, 0xbd,
	0x84, 0xe5, 0x17, 0x74, 0x6c, 0x15, 0xd5, 0xab, 0xf6, 0xff, 0x82, 0x37, 0x90, 0x7d, 0x96, 0x43,
	0xcb, 0x36, 0x51, 0xa6, 0x65, 0x96, 0x27, 0x91, 0xc2, 0xd8, 0xd5, 0xc2, 0xbb, 0x5d, 0x8f, 0xed,
	0x63, 0x6e, 0x6f, 0xa1, 0xf8, 0x88, 0x0a, 0x1d, 0xce, 0x0d, 0x4f, 0xeb, 0x70, 0xd8, 0xf5, 0xe1,
	0xb0, 0xeb, 0x4f, 0xfe, 0xb0, 0xab, 0xc5, 0xae, 0x20, 0xe5, 0xdd, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xab, 0xd9, 0x86, 0xa9, 0x13, 0x03, 0x00, 0x00,
}
